# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "harshvardhan-terragrunt"
    key     = "./sandbox/terraform.tfstate"
    profile = "sandbox"
    region  = "us-west-2"
  }
}
